# .github/workflows/deploy.yml

name: Deploy to Cloudflare Pages with Wrangler

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      # --- 圖片壓縮等準備工作可以保留 ---
      - name: Prepare deployment assets
        run: |
          # 安裝 ImageMagick
          sudo apt-get update
          sudo apt-get install -y imagemagick
          # 壓縮圖片 (可選)
          find out/images -name "*.png" -size +20M -exec magick {} -quality 85 -resize 2048x2048\> {} \;

      - name: Deploy to Cloudflare Pages
        run: npx wrangler pages deploy # <--- 注意看這裡的變化！
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}